### ISSUE TITLE
Disable snipcart, have "Purchase Now" button link elsewhere

### ISSUE THREAD

**Issue by ScriptAutomate** [gethugothemes/influencer-hugo#12]
This may be a feature request.

I'd like to remove the snipcart functionality from the site, and simply have the "Purchase Now" button be a link button like other sections of the page make use of.

**Comment by tfsomrat** [comment]
Hello @ScriptAutomate 

You can simply remove the `button` and add an `a` tag with `href` to do that. for this, you need to know some basic knowledge of HTML and Hugo. 

I also let you know that we are giving customization service [paid]. if you need any customization, you can contact us at mehedi@themefisher.com.
